apiVersion: v1
kind: Service
metadata:
  name: swagger-editor
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: swagger-editor
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
