apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: postgresql-homelab-hub
  namespace: flux-system
spec:
  interval: 1m
  path: ./infrastructure/databases/postgresql/postgresql
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: default  